language: node_js
node_js:
  - "stable"
cache:
  directories:
  - "node_modules"
script:
  - cd web
  - npm install
  - npm test
  - npm run build
deploy:
  provider: surge
  project: ./web/build/
  domain: fodmap.surge.sh
  skip_cleanup: true